#Equity Assessment of Global Mitigation Pathways 

#Explanatory comments are prefixed by #.
#Instructions for editing code are prefixed by ##. 

##Set working directory to local directory
setwd("~/AR6 Global")

#####Loading and preparation of datasets######

#Load IPCC scenario data sets
##Change path name here to local directory
ipcc_global<-read.csv("/home/AR6 Global/1648976687084-AR6_Scenarios_Database_World_v1.0/AR6_global_vetted.csv")
ipcc_r10<-read.csv("/home/AR6 Global/1648976423186-AR6_Scenarios_Database_R10_regions_v1.0/AR6_Scenarios_Database_R10_regions_v1.0.csv")

#A unique scenario is generated by combining the "Model" name and the "scenario" name
ipcc_global$ModSc<-paste(ipcc_global$Model, ipcc_global$Scenario, sep=" ")
ipcc_r10$ModSc<-paste(ipcc_r10$model, ipcc_r10$scenario, sep= " ")

#Subset only scenarios in the C1 to C4 categories

ipcc_global<-subset(ipcc_global, ipcc_global$Category %in% c("C1", "C2", "C3", "C4"))

#Remove additional spaces in model name strings

library(stringr)
ipcc_global$Model<-trimws(ipcc_global$Model)
ipcc_global$Model<-str_squish(ipcc_global$Model)

#Number of overlapping scenarios between IPCC Global and IPCC R10 databases
length(intersect(ipcc_global$ModSc, ipcc_r10$ModSc))

#Identify scenarios common to Global and R10 databases
global_r10_com_modsc<-intersect(ipcc_global$ModSc, ipcc_r10$ModSc)
length(global_r10_com_modsc)

#Subset the IPCC R10 database to include only the overlapping scenarios
ipcc_r10_short<-subset(ipcc_r10, ipcc_r10$ModSc %in% global_r10_com_modsc)

##SELECT VARIABLES HERE
#Add/remove variables to be analyzed here. 
vars<-c("Population","Emissions|CO2", "Primary Energy", "Primary Energy|Coal", "Primary Energy|Oil", "Primary Energy|Gas", "GDP|PPP", "Consumption","Final Energy|Electricity", "Secondary Energy|Electricity", "Carbon Sequestration|CCS", "Carbon Sequestration|Land Use")

#Downselect the R10 database to include only the variables of interest. 
ipcc_r10_short<-subset(ipcc_r10_short, ipcc_r10_short$variable %in% vars)

#Assign categories to scenarios in the R10 database by mapping with the Global database
for (i in 1:nrow(ipcc_r10_short)){
  ipcc_r10_short$Category[i]<-ipcc_global$Category[ipcc_r10_short$ModSc[i]==ipcc_global$ModSc]
}

#Select years 2020 to 2100
ipcc_r10_short<-ipcc_r10_short[,c(1:5, 17, 22:39)]

#Load data for POLES models from the ENGAGE database
#Regional data for POLES scenarios are not available in the R10 dataset. So they are taken
#from the source database ENGAGE and merged with the IPCC R10 dataset. 
poles_engage_r10<-read.csv("ENGAGE_R10_POLES.csv")
poles_engage_r10<-poles_engage_r10[,c(2:25)]
colnames(poles_engage_r10)<-colnames(ipcc_r10_short)
#Match POLES region names with IPCC R10 region names
poles_engage_r10$region[poles_engage_r10$region=="Sub-Saharan Africa (R10)"]<-"R10AFRICA"
poles_engage_r10$region[poles_engage_r10$region=="China (R10)"]<-"R10CHINA+"
poles_engage_r10$region[poles_engage_r10$region=="European Union and Western Europe (R10)"]<-"R10EUROPE"
poles_engage_r10$region[poles_engage_r10$region=="South Asia (R10)"]<-"R10INDIA+"
poles_engage_r10$region[poles_engage_r10$region=="Latin America (R10)"]<-"R10LATIN_AM"
poles_engage_r10$region[poles_engage_r10$region=="Middle East (R10)"]<-"R10MIDDLE_EAST"
poles_engage_r10$region[poles_engage_r10$region=="North America (R10)"]<-"R10NORTH_AM"
poles_engage_r10$region[poles_engage_r10$region=="Pacific OECD (R10)"]<-"R10PAC_OECD"
poles_engage_r10$region[poles_engage_r10$region=="Reforming Economies (R10)"]<-"R10REF_ECON"
poles_engage_r10$region[poles_engage_r10$region=="Other Asian countries (R10)"]<-"R10REST_ASIA"
poles_engage_r10$region[poles_engage_r10$region=="Other (R10)"]<-"R10ROWO"

#Merge POLES scenarios with the IPCC R10 database
ipcc_r10_short<-rbind(ipcc_r10_short, poles_engage_r10)

#############################################################################

#CALCULATE YEAR OF NET ZERO

#Different models report values at different time intervals. 
#Models are grouped based on the differing time intervals, and their CO2 emission curves
#are interpolated separately for each group. 
#This grouping is to handle the interpolation by linear fitting, which requires common
#number of time data points and CO2 data points to run the lm function. 
#This also ensures the full set of available raw values are used from each model. 

#List of models in the R10 database. 
model_list<-unique(ipcc_r10_short$model)

#Grouping of models by different time intervals 
co2<-ipcc_r10_short_co2<-subset(ipcc_r10_short, ipcc_r10_short$variable=="Emissions|CO2")
years_1<-c(2020, 2025, 2030, 2035, 2040, 2045, 2050, 2060, 2070, 2080, 2090, 2100) 
co2_1<-subset(co2, co2$model %in% model_list[c(2,7,21)])
years_2<- c(2020, 2025, 2030, 2035, 2040, 2045, 2050, 2055, 2060, 2065, 2070, 2075, 2080, 2085, 2090, 2095, 2100)
co2_2<-subset(co2, co2$model %in% model_list[c(1,3,4,5,6,8,20)])
years_3<- c(2020, 2025, 2030, 2035, 2040, 2045, 2050, 2055, 2060, 2070, 2080, 2090, 2100)
co2_3<-subset(co2, co2$model %in% model_list[c(9,10,12,13,14,15,16,17,18)])
years_4<- c(2020, 2030, 2040, 2050, 2060, 2070, 2080, 2090, 2100)
co2_4<- subset(co2, co2$model %in% model_list[c(11,19)])

for (i in 1:nrow(co2_1)){
  #Co2 emissions time series- columns selected based on model-specific time steps
  vals<-as.numeric(co2_1[i, c(6:12, 14, 16, 18, 20, 22)])
  #If there are negative values in the emissions time series, look for netzero year. If not, set the
  #net zero year to be NA. 
  if (sum(vals<0)!=0){
    #identify the datapoint where co2 goes negative
    negindex<-which(vals<0)[1]
    # Select the points where emissions goes from positive to negative
    y<- c(vals[negindex-1], vals[negindex])
    x<-c(years_1[negindex-1], years_1[negindex])
    #Interpolate between the positive and negative CO2 values
    model<-lm(y~x)
    #Intercept with the time axis gives the net zero year
    net_zero_year<- round(as.numeric(model$coefficients[1])/as.numeric(-model$coefficients[2]))
    co2_1$Net_Zero_Year[i]<-net_zero_year
  }else{
    co2_1$Net_Zero_Year[i]<-NA}
}

for (i in 1:nrow(co2_2)){
  vals<-as.numeric(co2_2[i, c(6:22)])
  if (sum(vals<0)!=0){
    negindex<-which(vals<0)[1]
    y<- c(vals[negindex-1], vals[negindex])
    x<-c(years_2[negindex-1], years_2[negindex])
    model<-lm(y~x)
    net_zero_year<- round(as.numeric(model$coefficients[1])/as.numeric(-model$coefficients[2]))
    co2_2$Net_Zero_Year[i]<-net_zero_year
  }else{
    co2_2$Net_Zero_Year[i]<-NA}
}

for (i in 1:nrow(co2_3)){
  vals<-as.numeric(co2_3[i, c(6:14, 16, 18, 20, 22)])
  if (sum(vals<0)!=0){
    negindex<-which(vals<0)[1]
    y<- c(vals[negindex-1], vals[negindex])
    x<-c(years_3[negindex-1], years_3[negindex])
    model<-lm(y~x)
    net_zero_year<- round(as.numeric(model$coefficients[1])/as.numeric(-model$coefficients[2]))
    co2_3$Net_Zero_Year[i]<-net_zero_year
  }else{
    co2_3$Net_Zero_Year[i]<-NA}
}

for (i in 1:nrow(co2_4)){
  vals<-as.numeric(co2_4[i, seq(6, 22, 2)])
  if (sum(vals<0)!=0){
    negindex<-which(vals<0)[1]
    y<- c(vals[negindex-1], vals[negindex])
    x<-c(years_4[negindex-1], years_4[negindex])
    model<-lm(y~x)
    net_zero_year<- round(as.numeric(model$coefficients[1])/as.numeric(-model$coefficients[2]))
    co2_4$Net_Zero_Year[i]<-net_zero_year
  }else{
    co2_4$Net_Zero_Year[i]<-NA}
}

co2<-rbind(co2_1, co2_2, co2_3, co2_4)

##################################################################################################


#Calculate the area under the CO2 curve from 2020 till the year of net zero

#Calculate the area under the curve from 2020 till Net Zero year
#If the region does not attain net zero, then calculate cumulative emissions
#till 2100, the end of the century.

library("pracma")

for (i in 1:nrow(co2_1)){
  #i=1
  if(!is.na(co2_1[i,25])){
    vals<-as.numeric(co2_1[i, c(6:12, 14, 16, 18, 20, 22)])
    cutoffindex<-(which(vals<0)[1])-1
    y<-c(as.numeric(vals[1:cutoffindex]),0)
    x<-c(years_1[1:cutoffindex], as.numeric(co2_1[i,25]))
    AUC<-trapz(x,y)
    co2_1$cumCo2[i]<-AUC
  }else{
    y<-as.numeric(co2_1[i, c(6:12, 14, 16, 18, 20, 22)])
    x<-years_1
    AUC<-trapz(x,y)
    co2_1$cumCo2[i]<-AUC
  }
}

co2_1$cumCo2<-co2_1$cumCo2/1000

#co2 2

for (i in 1:nrow(co2_2)){
  #i=1
  if(!is.na(co2_2[i,25])){
    vals<-as.numeric(co2_2[i,c(6:22)])
    cutoffindex<-(which(vals<0)[1])-1
    y<-c(as.numeric(vals[1:cutoffindex]),0)
    x<-c(years_2[1:cutoffindex], as.numeric(co2_2[i,25]))
    AUC<-trapz(x,y)
    co2_2$cumCo2[i]<-AUC
  }else{
    y<-as.numeric(co2_2[i,c(6:22)])
    x<-years_2
    AUC<-trapz(x,y)
    co2_2$cumCo2[i]<-AUC
  }
}

co2_2$cumCo2<-co2_2$cumCo2/1000

#co2 3 

for (i in 1:nrow(co2_3)){
  #i=1
  if(!is.na(co2_3[i,25])){
    vals<-as.numeric(co2_3[i, c(6:14, 16, 18, 20, 22)])
    cutoffindex<-(which(vals<0)[1])-1
    y<-c(as.numeric(vals[1:cutoffindex]),0)
    x<-c(years_3[1:cutoffindex], as.numeric(co2_3[i,25]))
    AUC<-trapz(x,y)
    co2_3$cumCo2[i]<-AUC
  }else{
    y<-as.numeric(co2_3[i, c(6:14, 16, 18, 20, 22)])
    x<-years_3
    AUC<-trapz(x,y)
    co2_3$cumCo2[i]<-AUC
  }
}

co2_3$cumCo2<-co2_3$cumCo2/1000

#co2 4 

for (i in 1:nrow(co2_4)){
  #i=1
  if(!is.na(co2_4[i,25])){
    vals<-as.numeric(co2_4[i, seq(6, 22, 2)])
    cutoffindex<-(which(vals<0)[1])-1
    y<-c(as.numeric(vals[1:cutoffindex]),0)
    x<-c(years_4[1:cutoffindex], as.numeric(co2_4[i,25]))
    AUC<-trapz(x,y)
    co2_4$cumCo2[i]<-AUC
  }else{
    y<-as.numeric(co2_4[i, seq(6, 22, 2)])
    x<-years_4
    AUC<-trapz(x,y)
    co2_4$cumCo2[i]<-AUC
  }
}

co2_4$cumCo2<-co2_4$cumCo2/1000

co2<-rbind(co2_1, co2_2, co2_3, co2_4)

##############################################################################

#BINNING

#For each model, for each region, calculate the mean of cum Co2 
#with 10 GtCo2 sized bins. Identify the scenarios in each bin and 
#obtain the median values of other variables for scenarios in that bin. 
#Then take the mean value of the variable across bins 

#Assign bin numbers to each scenario in co2 based on cumco2

co2$bin<-trunc(co2$cumCo2/10)+1
table(co2$bin)

ipcc_R10_short_vars<-ipcc_r10_short

#Map bin numbers from cum co2 data to the ipcc r10 dataset for all variables
#Note that bin number is specific to a scenario and  the region
#so the common key for mapping is a combination of region and model_scenario

for (i in 1:nrow(ipcc_R10_short_vars)){
  ipcc_R10_short_vars$bin[i]<-co2$bin[ipcc_R10_short_vars$ModSc[i]==co2$ModSc & ipcc_R10_short_vars$region[i]==co2$region]
}

#########################################################################################

#Per capita values of all variables

ipcc_r10_percapita_vars<-as.data.frame(matrix(data= NA, nrow=0, ncol=25))

for (i in 1:length(unique(ipcc_R10_short_vars$ModSc))){
  #i=1
  for (j in 1:length(unique(ipcc_R10_short_vars$variable))){
    #j=1
    for (k in 1:length(unique(ipcc_R10_short_vars$region))){
      #k=1
      #Get population time series for the particular scenario
      pop<-ipcc_R10_short_vars[ipcc_R10_short_vars$ModSc == unique(ipcc_R10_short_vars$ModSc)[i] & ipcc_R10_short_vars$variable == "Population" & ipcc_R10_short_vars$region == unique(ipcc_R10_short_vars$region)[k],] 
      #Get the variable time series
      var<-ipcc_R10_short_vars[ipcc_R10_short_vars$ModSc == unique(ipcc_R10_short_vars$ModSc)[i] & ipcc_R10_short_vars$variable == unique(ipcc_R10_short_vars$variable)[j] & ipcc_R10_short_vars$region== unique(ipcc_R10_short_vars$region)[k],]
      
      if (nrow(var) != 0 & nrow(pop)!=0){
        var_j<- (var[, 6:22]/pop [,6:22])
        per_cap_row<-data.frame(var$model, var$scenario, var$region, var$variable, var$unit, var_j, var$ModSc, var$Category, var$bin)
        ipcc_r10_percapita_vars<- rbind(ipcc_r10_percapita_vars, per_cap_row)
        print(c(i,j,k))
      }
    }
  }
}

#Remove variable 'population' from the percapita dataset
ipcc_r10_percapita_vars2<-subset(ipcc_r10_percapita_vars, ipcc_r10_percapita_vars$var.variable != "Population")
#Assign column names 
colnames(ipcc_r10_percapita_vars2)[1:5]<-c("Model", "Scenario", "Region", "Variable", "Unit")
colnames(ipcc_r10_percapita_vars2)[23:25]<-c("ModSc", "Category", "bin")

#Assign bin numbers to the percapita dataset
for (i in 1:nrow(ipcc_r10_percapita_vars2)){
  ipcc_r10_percapita_vars2$bin[i]<-co2$bin[ipcc_r10_percapita_vars2$ModSc[i]==co2$ModSc & ipcc_r10_percapita_vars2$Region[i]==co2$region]
}

write.csv(ipcc_r10_percapita_vars2, "IPCC_R10_Percapita_Mastersheet.csv")
write.csv(ipcc_R10_short_vars, "IPCC_R10_Variables_Mastersheet.csv")
#########################################################################

#Load per capita and absolute variables mastersheet

ipcc_r10_percapita_vars2<-read.csv("IPCC_R10_Percapita_Mastersheet.csv")
ipcc_R10_short_vars<-read.csv("IPCC_R10_Variables_Mastersheet.csv")
ipcc_R10_short_vars<-ipcc_R10_short_vars[,2:26]
##############################################################################

#Generate bin-wise distribution of values for each variable, take the median 
#within each bin and average across bins

#List of variables in the analysis
vars

#2- co2, 3- PE, 4- PE coal, 5-PE oil, 6-PE Gas, 7-GDP|PPP, 8- Consumption, 9- Final energy|electricity
# 10- Sec Energy, 11- C Seq CCS, 12- CCS Seq Land Use

#Select variable to be averaged across scenarios 
varsindex=8

#For per capita values 
mean_var_df<-as.data.frame(matrix(data=NA, nrow=0, ncol=4))

for (i in 1:length(model_list)){
  #i=14
  model<-model_list[i]
  ipcc_r10_percapita_vars2_model<-subset(ipcc_r10_percapita_vars2, ipcc_r10_percapita_vars2$Model==model)
  model_regionlist<-unique(ipcc_r10_percapita_vars2_model$Region)
  for (j in 1:length(model_regionlist)){
    #j=1
    region=model_regionlist[j]
    ipcc_r10_percapita_vars2_model_reg<-subset(ipcc_r10_percapita_vars2_model, ipcc_r10_percapita_vars2_model$Region==model_regionlist[j])
    for (k in 1:length(unique(ipcc_r10_percapita_vars2_model_reg$Category))){
      #k=1
      categ<-unique(ipcc_r10_percapita_vars2_model_reg$Category)[k]
      ipcc_r10_percapita_vars2_model_reg_cat<-subset(ipcc_r10_percapita_vars2_model_reg, ipcc_r10_percapita_vars2_model_reg$Category == categ)
      binmediansum2<-0 #This is for summing the medians across bins for the selected variable
      for (l in 1:length(unique(ipcc_r10_percapita_vars2_model_reg_cat$bin))){
        #l=2
        bin_num<-unique(ipcc_r10_percapita_vars2_model_reg_cat$bin)[l]
        ipcc_r10_percapita_vars2_model_reg_cat_bin<-subset(ipcc_r10_percapita_vars2_model_reg_cat, ipcc_r10_percapita_vars2_model_reg_cat$bin==bin_num)
        bin_median_vars<-median(ipcc_r10_percapita_vars2_model_reg_cat_bin$X2050[ipcc_r10_percapita_vars2_model_reg_cat_bin$Variable==vars[varsindex]], na.rm = T)
        if (!is.na(bin_median_vars)){
        binmediansum2=binmediansum2+bin_median_vars
        }
        }
      mean_vars<-binmediansum2/length(unique(ipcc_r10_percapita_vars2_model_reg_cat$bin))
      if(!is.na(mean_vars)){
      mean_var_df_row<-data.frame(model, region, categ, mean_vars)
      mean_var_df<-rbind(mean_var_df, mean_var_df_row)
      }
    }
  }
}

#mean_var_df$mean_vars<-mean_var_df$mean_vars*1000 #This is to adjust units for PE variables only
write.csv(mean_var_df, "~/AR6 Global/New_Vals/Consumptionpercap_2050_revised.csv")

##########################################################################################

#For cumulative CO2 

mean_cumCo2_df<-as.data.frame(matrix(data=NA, nrow=0, ncol=4))

for (i in 1:length(model_list)){
  #i=1
  model<-model_list[i]
  co2_model<-subset(co2, co2$model==model_list[i])
  model_regionlist<-unique(co2_model$region)
  for (j in 1:length(model_regionlist)){
    #j=2
    region=model_regionlist[j]
    co2_model_reg<-subset(co2_model, co2_model$region==model_regionlist[j])
    for (k in 1:length(unique(co2_model_reg$Category))){
      #k=4
      categ<-unique(co2_model_reg$Category)[k]
      co2_model_reg_cat<-subset(co2_model_reg, co2_model_reg$Category==categ)
      binmediansum<-0
      for (l in 1:length(unique(co2_model_reg_cat$bin))){
        bin_num<-unique(co2_model_reg_cat$bin)[l]
        bin_median_cumco2<-median(co2_model_reg_cat$cumCo2[co2_model_reg_cat$bin==bin_num], na.rm=TRUE)
        binmediansum=binmediansum+bin_median_cumco2
        }
      mean_cumCo2<-binmediansum/length(unique(co2_model_reg_cat$bin))
      mean_cumCo2_df_row<-data.frame(model, region, categ, mean_cumCo2)
      mean_cumCo2_df<-rbind(mean_cumCo2_df, mean_cumCo2_df_row)
    }
  }
}

write.csv(mean_cumCo2_df, "~/AR6 Global/New_Vals/cumCo2_revised.csv")
######################################################################################

#Calculate peaking years

years<-seq(2020, 2100,5)

for (i in 1:nrow(co2)){
  co2_vals<-as.numeric(co2[i,c(6:22)])
  max_co2<-max(co2_vals, na.rm = T)
  co2$peak_year[i]<-years[which(co2_vals==max_co2)]
}

########################################
#For net zero year and peaking year

mean_year_df<-as.data.frame(matrix(data=NA, nrow=0, ncol=4))

for (i in 1:length(model_list)){
  #i=1
  model<-model_list[i]
  co2_model<-subset(co2, co2$model==model_list[i])
  model_regionlist<-unique(co2_model$region)
  for (j in 1:length(model_regionlist)){
    #j=2
    region=model_regionlist[j]
    co2_model_reg<-subset(co2_model, co2_model$region==model_regionlist[j])
    for (k in 1:length(unique(co2_model_reg$Category))){
      #k=1
      categ<-unique(co2_model_reg$Category)[k]
      co2_model_reg_cat<-subset(co2_model_reg, co2_model_reg$Category==categ)
      binmediansum3<-0
      for (l in 1:length(unique(co2_model_reg_cat$bin))){
        bin_num<-unique(co2_model_reg_cat$bin)[l]
        ##Comment the next line for net zero year calculation
        #bin_median_year<-median(co2_model_reg_cat$peak_year[co2_model_reg_cat$bin==bin_num], na.rm=T)
        ##Uncomment the following four lines for net zero year
        bin_median_year<-median(co2_model_reg_cat$Net_Zero_Year[co2_model_reg_cat$bin==bin_num], na.rm=T)
        if (is.na(bin_median_year)==T){
          bin_median_year<-0
        }
        binmediansum3=binmediansum3+bin_median_year
      }
      #mean_year<-binmediansum3/length(unique(co2_model_reg_cat$bin))
      mean_year<-binmediansum3/length(unique(co2_model_reg_cat$bin[!is.na(co2_model_reg_cat$Net_Zero_Year)]))
      mean_year_df_row<-data.frame(model, region, categ, round(mean_year))
      mean_year_df<-rbind(mean_year_df, mean_year_df_row)
    }
  }
}

write.csv(mean_year_df, "~/AR6 Global/NetZeroyears.csv")

#################################################################################


#Cumulative net negative emissions from 2020 till year of net zero
#Like in the calculation of net zero year above, the models are grouped by the 
#time intervals in which they report values so that all raw values are utilised before interpolation
#The area under the curve is calculated to give the cumulative CO2 sequestered

co2ccs<-subset(ipcc_R10_short_vars, ipcc_R10_short_vars$variable=="Carbon Sequestration|CCS")

years_1<-c(2020, 2025, 2030, 2035, 2040, 2045, 2050, 2060, 2070, 2080, 2090, 2100) 
co2ccs_1<-subset(co2ccs, co2ccs$model %in% model_list[c(2,7,21)])
years_2<- c(2020, 2025, 2030, 2035, 2040, 2045, 2050, 2055, 2060, 2065, 2070, 2075, 2080, 2085, 2090, 2095, 2100)
co2ccs_2<-subset(co2ccs, co2ccs$model %in% model_list[c(1,3,4,5,6,8,20)])
years_3<- c(2020, 2025, 2030, 2035, 2040, 2045, 2050, 2055, 2060, 2070, 2080, 2090, 2100)
co2ccs_3<-subset(co2ccs, co2ccs$model %in% model_list[c(9,10,12,13,14,15,16,17,18)])
years_4<- c(2020, 2030, 2040, 2050, 2060, 2070, 2080, 2090, 2100)
co2ccs_4<- subset(co2ccs, co2ccs$model %in% model_list[c(11,19)])

for (i in 1:nrow(co2ccs_1)){
  #i=1
  co2dat<-subset(co2_1, co2_1$ModSc==co2ccs_1$ModSc[i] & co2_1$region==co2ccs_1$region[i])
  if(!is.na(co2dat[1,25])){
    vals<-as.numeric(co2dat[1, c(6:12, 14, 16, 18, 20, 22)])
    cutoffindex<-(which(vals<0)[1])-1
    vals_ccs<-as.numeric(co2ccs_1[i, c(6:12, 14, 16, 18, 20, 22)])
    vals2<-as.numeric(vals_ccs[1:(cutoffindex+1)])
    fitmodel<-lm(vals2~years_1[1:(cutoffindex+1)])
    final_y<-fitmodel$coefficients[2]*as.numeric(co2dat[1,25])+fitmodel$coefficients[1]
    y<-c(as.numeric(vals2[1:cutoffindex]),as.numeric(final_y))
    x<-c(years_1[1:cutoffindex], as.numeric(co2dat[1,25]))
    AUC<-trapz(x,y)
    co2ccs_1$cumCo2[i]<-AUC
  }else{
    y<-as.numeric(co2ccs_1[i, c(6:12, 14, 16, 18, 20, 22)])
    x<-years_1
    AUC<-trapz(x,y)
    co2ccs_1$cumCo2[i]<-AUC
  }
}

#Adjusting units to GtCO2
co2ccs_1$cumCo2<-co2ccs_1$cumCo2/1000

for (i in 1:nrow(co2ccs_2)){
  #i=1
  co2dat<-subset(co2_2, co2_2$ModSc==co2ccs_2$ModSc[i] & co2_2$region==co2ccs_2$region[i])
  if(!is.na(co2dat[1,25])){
    vals<-as.numeric(co2dat[1, c(6:22)])
    cutoffindex<-(which(vals<0)[1])-1
    vals_ccs<-as.numeric(co2ccs_2[i, c(6:22)])
    vals2<-as.numeric(vals_ccs[1:(cutoffindex+1)])
    fitmodel<-lm(vals2~years_2[1:(cutoffindex+1)])
    final_y<-fitmodel$coefficients[2]*as.numeric(co2dat[1,25])+fitmodel$coefficients[1]
    y<-c(as.numeric(vals2[1:cutoffindex]),as.numeric(final_y))
    x<-c(years_2[1:cutoffindex], as.numeric(co2dat[1,25]))
    AUC<-trapz(x,y)
    co2ccs_2$cumCo2[i]<-AUC
  }else{
    y<-as.numeric(co2ccs_2[i, c(6:22)])
    x<-years_2
    AUC<-trapz(x,y)
    co2ccs_2$cumCo2[i]<-AUC
  }
}

co2ccs_2$cumCo2<-co2ccs_2$cumCo2/1000

for (i in 1:nrow(co2ccs_3)){
  #i=1
  co2dat<-subset(co2_3, co2_3$ModSc==co2ccs_3$ModSc[i] & co2_3$region==co2ccs_3$region[i])
  if(!is.na(co2dat[1,25])){
    vals<-as.numeric(co2dat[1, c(6:14, 16, 18, 20, 22)])
    cutoffindex<-(which(vals<0)[1])-1
    vals_ccs<-as.numeric(co2ccs_3[i, c(6:14, 16, 18, 20, 22)])
    vals2<-as.numeric(vals_ccs[1:(cutoffindex+1)])
    fitmodel<-lm(vals2~years_3[1:(cutoffindex+1)])
    final_y<-fitmodel$coefficients[2]*as.numeric(co2dat[1,25])+fitmodel$coefficients[1]
    y<-c(as.numeric(vals2[1:cutoffindex]),as.numeric(final_y))
    x<-c(years_3[1:cutoffindex], as.numeric(co2[1,25]))
    AUC<-trapz(x,y)
    co2ccs_3$cumCo2[i]<-AUC
  }else{
    y<-as.numeric(co2ccs_3[i, c(6:14, 16, 18, 20, 22)])
    x<-years_3
    AUC<-trapz(x,y)
    co2ccs_3$cumCo2[i]<-AUC
  }
}

co2ccs_3$cumCo2<-co2ccs_3$cumCo2/1000

for (i in 1:nrow(co2ccs_4)){
  #i=1
  co2dat<-subset(co2_4, co2_4$ModSc==co2ccs_4$ModSc[i] & co2_4$region==co2ccs_4$region[i])
  if(!is.na(co2dat[1,25])){
    vals<-as.numeric(co2dat[1, seq(6, 22, 2)])
    cutoffindex<-(which(vals<0)[1])-1
    vals_ccs<-as.numeric(co2ccs_4[i, seq(6, 22, 2)])
    vals2<-as.numeric(vals_ccs[1:(cutoffindex+1)])
    fitmodel<-lm(vals2~years_4[1:(cutoffindex+1)])
    final_y<-fitmodel$coefficients[2]*as.numeric(co2dat[1,25])+fitmodel$coefficients[1]
    y<-c(as.numeric(vals2[1:cutoffindex]),as.numeric(final_y))
    x<-c(years_4[1:cutoffindex], as.numeric(co2dat[1,25]))
    AUC<-trapz(x,y)
    co2ccs_4$cumCo2[i]<-AUC
  }else{
    y<-as.numeric(co2ccs_4[i, seq(6, 22, 2)])
    x<-years_4
    AUC<-trapz(x,y)
    co2ccs_4$cumCo2[i]<-AUC
  }
}

co2ccs_4$cumCo2<-co2ccs_4$cumCo2/1000

co2ccs<-rbind(co2ccs_1, co2ccs_2, co2ccs_3, co2ccs_4)

##################################################################################


#Averaging cumulative ccs across models 

mean_ccs_df<-as.data.frame(matrix(data=NA, nrow=0, ncol=4))

for (i in 1:length(model_list)){
  #i=1
  model<-model_list[i]
  co2ccs_model<-subset(co2ccs, co2ccs$model==model_list[i])
  model_regionlist<-unique(co2ccs_model$region)
  for (j in 1:length(model_regionlist)){
    #j=2
    region=model_regionlist[j]
    co2ccs_model_reg<-subset(co2ccs_model, co2ccs_model$region==model_regionlist[j])
    for (k in 1:length(unique(co2ccs_model_reg$Category))){
      #k=4
      categ<-unique(co2ccs_model_reg$Category)[k]
      co2ccs_model_reg_cat<-subset(co2ccs_model_reg, co2ccs_model_reg$Category==categ)
      binmediansum<-0
      for (l in 1:length(unique(co2ccs_model_reg_cat$bin))){
        bin_num<-unique(co2ccs_model_reg_cat$bin)[l]
        bin_median_cumco2<-median(co2ccs_model_reg_cat$cumCo2[co2ccs_model_reg_cat$bin==bin_num], na.rm=TRUE)
        binmediansum=binmediansum+bin_median_cumco2
        }
      mean_ccscumCo2<-binmediansum/length(unique(co2ccs_model_reg_cat$bin))
      if (!is.na(mean_ccscumCo2)){
      mean_ccs_df_row<-data.frame(model, region, categ, mean_ccscumCo2)
      mean_ccs_df<-rbind(mean_ccs_df, mean_ccs_df_row)}
    }
  }
}

write.csv(mean_ccs_df, "~/AR6 Global/CCS.csv")

##################################################################################################


#Correlation between GDP, emissions and energy variables 

categories<-c("C1","C2", "C3", "C4")

i=1

PE_cat<- subset(ipcc_r10_percapita_vars2, ipcc_r10_percapita_vars2$Variable=="Primary Energy" & ipcc_r10_percapita_vars2$Category==categories[i])
CO2_cat<- subset(ipcc_r10_percapita_vars2, ipcc_r10_percapita_vars2$Variable=="Emissions|CO2" & ipcc_r10_percapita_vars2$Category==categories[i])
GDP_cat<-subset(ipcc_r10_percapita_vars2, ipcc_r10_percapita_vars2$Variable=="GDP|PPP" & ipcc_r10_percapita_vars2$Category==categories[i])

commodsc_PECO2GDP<-intersect(intersect(PE_cat$ModSc, CO2_cat$ModSc), GDP_cat$ModSc)

PE_cat<-subset(PE_cat, PE_cat$ModSc %in% commodsc_PECO2GDP)
CO2_cat<-subset(CO2_cat, CO2_cat$ModSc %in% commodsc_PECO2GDP)
GDP_cat<-subset(GDP_cat, GDP_cat$ModSc %in% commodsc_PECO2GDP)

length(PE_cat$X2050)

cor.test(PE_cat$X2050, GDP_cat$X2050)
cor.test(PE_cat$X2050, CO2_cat$X2050)
cor.test(CO2_cat$X2050, GDP_cat$X2050)

#############################################################################################

#Get category-wise, model-wise distribution of scenarios
#"R10NORTH_AM" is chosen since this region is present for all scenarios across all models

model_list

for (i in 1:length(model_list)){
  a<-table(co2$Category[co2$model==model_list[i] & co2$region=="R10NORTH_AM"])
  print(cbind(model_list[i],a))
}

##################################################################################
